TOTAL_UNIQUE_TITLES_IN_MASTER: 73
TOTAL_BOOKS_IN_MASTER: 13342
TOTAL_BOOKS_IN_MASTER_FOR_PLACEMENT: 13238
TOTAL_VALUE_OF_SINGLE_UNIQUE_TITLES: 79886
MASTER_FANTASY_BOOK_LIST_PATH: D:\Dropbox\My Documents\Greg Documents\Programming\Python
  3\fantasy_books_workspace\fantasy_books\master_fantasy_book_list.xlsx
BOOKS_SPREADSHEET_OUT_PATH: D:\Dropbox\My Documents\Greg Documents\Programming\Python
  3\fantasy_books_workspace\fantasy_books\books_spreadsheet_out.xlsx
